; PROGRAM TO PRINT COLORED CAHRACTER IN THE TERMINAL

.MODEL SMALL

.STACK 100H

.DATA
    CHR DB 'T'  ; THE CHARACTER TO PRINT

.CODE

MAIN PROC FAR
    MOV AX, @DATA
    MOV DS, AX

    ; PRINT COLORED TEXT
    MOV AH, 09H
    MOV AL, CHR   ; CHARACTER TO PRINT
    MOV BH, 00H   ; PAGE NUMBER
    MOV BL, 42H   ; COLOR ATTRIBUTE (FG: Red, BG: Green)
    MOV CX, 1     ; NUMBER OF TIMES TO PRINT CHARACTER
    INT 10H

    ; EXIT PROGRAM
    MOV AX, 4CH
    INT 21H
MAIN ENDP

END MAIN
